import { readFileSync } from 'node:fs';
import { escape, safeUrl, articleContent, words } from './content.js';
import { siteUrl, CATEGORIES } from './config.js';
function shell() { return JSON.parse(readFileSync(new URL('./site-shell.json', import.meta.url), 'utf8')); }
function structured(value) { return JSON.stringify(value).replace(/</g, '\\u003c'); }
export function layout({ title, description, path, content, graph = [], image, noindex = false }) {
  const shared = shell(), base = siteUrl(), canonical = base + path;
  return `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(title)}</title><meta name="description" content="${escape(description)}"><link rel="canonical" href="${escape(canonical)}">${noindex ? '<meta name="robots" content="noindex,nofollow">' : ''}<meta property="og:type" content="${graph.some(v => v['@type'] === 'BlogPosting') ? 'article' : 'website'}"><meta property="og:title" content="${escape(title)}"><meta property="og:description" content="${escape(description)}"><meta property="og:url" content="${escape(canonical)}">${safeUrl(image) ? `<meta property="og:image" content="${escape(image)}"><meta name="twitter:card" content="summary_large_image">` : '<meta name="twitter:card" content="summary">'}<link rel="preconnect" href="https://fonts.googleapis.com"><link href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400;0,500;0,600;1,400;1,500&family=DM+Sans:wght@300;400;500&display=swap" rel="stylesheet"><link rel="stylesheet" href="/assets/site.css"><link rel="alternate" type="application/rss+xml" title="Mo’s Blog" href="${base}/rss.xml">${graph.length ? `<script type="application/ld+json">${structured({ '@context': 'https://schema.org', '@graph': graph })}</script>` : ''}</head><body>${shared.nav.replace('id="nav-blog"', 'id="nav-blog" aria-current="page"')}<main class="page active" id="main-content">${content}</main>${shared.footer}<script src="/assets/site.js" defer></script></body></html>`;
}
export function blogPage(posts = [], { category = '', page = 1, more = false } = {}) {
  const title = `${category ? category + ' | ' : ''}AI, Cloud & Technology Blog | Motunrayo Akinsete`;
  const cards = posts.map(post => `<a class="blog-card" href="/blog/${escape(post.slug)}/">${safeUrl(post.images?.[0]?.url) ? `<img src="${escape(post.images[0].url)}" alt="${escape(post.images[0].alt)}" width="1536" height="1024" loading="lazy">` : '<div class="blog-card-art" aria-hidden="true">✦</div>'}<div class="blog-card-body"><p class="blog-category">${escape(post.category)} · ${new Date(post.published_at).toLocaleDateString('en-GB', { timeZone: 'Africa/Lagos', year: 'numeric', month: 'short', day: 'numeric' })}</p><h2>${escape(post.title)}</h2><p>${escape(post.description)}</p><span>${Math.max(1, Math.ceil(words(post.body) / 220))} min read <span aria-hidden="true">↗</span></span></div></a>`).join('');
  const query = category ? `category=${encodeURIComponent(category)}&` : '';
  const graph = [{ '@type': 'Blog', '@id': siteUrl() + '/blog/#blog', name: 'Mo’s Blog', url: siteUrl() + '/blog/', author: { '@type': 'Person', name: 'Motunrayo Akinsete', url: siteUrl() + '/about/' }, blogPost: posts.map(post => ({ '@type': 'BlogPosting', headline: post.title, url: `${siteUrl()}/blog/${post.slug}/` })) }];
  return layout({ title, description: 'Ideas, research and practical perspectives on AI, cloud computing, cybersecurity, technology and life from Motunrayo Akinsete.', path: `/blog/${category || page > 1 ? '?' + query + (page > 1 ? `page=${page}` : '') : ''}`.replace(/[?&]$/, ''), graph, content: `<section class="section dark blog-hero"><p class="sec-eyebrow">Notes from Mo</p><h1 class="sec-title on-dark">Ideas worth<br><em>thinking about.</em></h1><p>AI research, cloud computing, cybersecurity and the human side of technology. A space for useful questions, fresh perspectives and a few personal notes.</p></section><section class="section cloud"><nav class="blog-categories" aria-label="Blog topics"><a href="/blog/" ${!category ? 'aria-current="page"' : ''}>All posts</a>${CATEGORIES.map(c => `<a href="/blog/?category=${encodeURIComponent(c)}" ${category === c ? 'aria-current="page"' : ''}>${escape(c)}</a>`).join('')}</nav>${posts.length ? `<div class="blog-grid">${cards}</div>` : '<div class="blog-empty"><span aria-hidden="true">✦</span><h2>A few good ideas are on their way.</h2><p>New essays will appear here after editorial review. In the meantime, explore my research and product work.</p><a class="btn-primary" href="/research/">Explore AI research ↗</a></div>'}<div class="blog-pagination">${page > 1 ? `<a href="/blog/?${query}page=${page - 1}">← Newer posts</a>` : ''}${more ? `<a href="/blog/?${query}page=${page + 1}">Older posts →</a>` : ''}</div></section>` });
}
export function postPage(post, preview = false) {
  const base = siteUrl(), url = `${base}/blog/${post.slug}/`;
  const graph = [{ '@type': 'BlogPosting', '@id': url + '#article', headline: post.title, description: post.description, image: post.images.map(i => safeUrl(i.url)).filter(Boolean), datePublished: post.published_at || undefined, dateModified: post.updated_at, author: { '@type': 'Person', name: 'Motunrayo Akinsete', url: base + '/about/' }, publisher: { '@type': 'Person', name: 'Motunrayo Akinsete', url: base + '/about/' }, mainEntityOfPage: url }, { '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'Home', item: base + '/' }, { '@type': 'ListItem', position: 2, name: 'Blog', item: base + '/blog/' }, { '@type': 'ListItem', position: 3, name: post.title, item: url }] }];
  const date = post.published_at ? new Date(post.published_at).toLocaleDateString('en-GB', { timeZone: 'Africa/Lagos', year: 'numeric', month: 'long', day: 'numeric' }) : 'Unpublished draft';
  return layout({ title: `${post.title} | Motunrayo Akinsete`, description: post.description, path: `/blog/${post.slug}/`, image: post.images?.[0]?.url, graph, noindex: preview, content: `<article class="blog-article"><header class="article-header"><a href="/blog/" class="text-link">← Back to the blog</a>${preview ? '<p class="preview-notice">Private editorial preview · not published</p>' : ''}<p class="sec-eyebrow blue">${escape(post.category)}</p><h1>${escape(post.title)}</h1><p class="article-deck">${escape(post.social_excerpt || post.description)}</p><div class="article-byline"><img src="/assets/portrait-11ee9b31918e.png" alt="" width="44" height="44"><div><a href="/about/">Motunrayo Akinsete</a><span>${date} · ${Math.max(1, Math.ceil(words(post.body) / 220))} min read</span></div></div></header><div class="article-content">${articleContent(post)}</div><aside class="article-author"><h2>About the author</h2><p>Motunrayo Akinsete is an AI product manager, researcher, consultant and trainer based in Nigeria. Explore her work in responsible AI, product building and practical AI adoption.</p><a href="/about/">Meet Mo →</a></aside><div class="article-end"><a class="btn-primary" href="/blog/">More from the blog</a><a class="text-link" href="/book/">Work with Mo ↗</a></div></article>` });
}
export function exportHtml(post) {
  return `<!DOCTYPE html><html><head><meta charset="UTF-8"><title>${escape(post.title)}</title></head><body><article><h1>${escape(post.title)}</h1><p>${escape(post.social_excerpt || post.description)}</p><p>By Motunrayo Akinsete</p>${articleContent(post)}</article></body></html>`;
}
